services:

  aixm-client:
    container_name: aixm-client
    image: aixm/aixm-client:latest
    restart: unless-stopped
    depends_on:
      - aixm-proxy
    networks:
      - aixm

  aixm-server:
    container_name: aixm-server
    image: aixm/aixm-server:latest
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - ./aixm-server/storage:/var/www/storage
    env_file:
      - .env
    depends_on:
      - aixm-postgres
    networks:
      - aixm

  aixm-queue:
    container_name: aixm-queue
    image: aixm/aixm-server:latest
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - ./aixm-server/storage:/var/www/storage
    depends_on:
      - aixm-server
    command: /bin/bash /opt/bin/queue.sh &>/dev/null &
    networks:
      - aixm

  aixm-nginx:
    container_name: aixm-nginx
    image: aixm/aixm-nginx:latest
    restart: unless-stopped
    volumes:
      - ./aixm-server/storage:/var/www/storage:ro
    depends_on:
      - aixm-server
    networks:
      - aixm

  aixm-postgres:
    container_name: aixm-postgres
    image: aixm/aixm-postgres:latest
    restart: unless-stopped
    volumes:
      - ./aixm-server/docker/postgres/postgresql/data:/var/lib/postgresql/data
      - ./aixm-server/docker/postgres/tmp/data:/tmp/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - LANG=${DB_LANG}
    networks:
      - aixm

  aixm-redis:
    container_name: aixm-redis
    image: aixm/aixm-redis
    build:
      context: .
      dockerfile: ./aixm-server/docker/redis/Dockerfile
    restart: unless-stopped
    volumes:
      - aixm-redis-data:/data:rw
    networks:
      - aixm

  aixm-proxy:
    container_name: aixm-proxy
    image: aixm/aixm-nginx:latest
    restart: unless-stopped
    ports: [ "${CLIENT_WEBPORT}:80" ]
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - localnode:${LOCALNODE:-172.17.0.1}
    depends_on:
      - aixm-nginx
    networks:
      - aixm

volumes:
  aixm-redis-data:

networks:
  aixm:
    driver: bridge


